name: CI

on: [push]

jobs:
  build:
    name: Testing on ${{ matrix.os }} with Python version ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7']
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Pip install
        run: pip install -r requirements.txt && pip install coverage

      - name: Run tests with coverage
        run: coverage run --source=pyais -m unittest discover tests && coverage report -m

      - name: Run Flake8
        run: pip install flake8 flake8
