name: Build & Test

# Trigger on push
on: push

jobs:
  build:
    name: Testing on ${{ matrix.os }} with Python version ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7', '3.8']
        os: ['ubuntu-latest', 'macOS-latest']
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests
